# METfilters:
#     name: MetFilterRDF
#     path: Base.Modules.METfilters
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year

# LumiFilters:
#     name: lumiFilterRDF
#     path: Base.Modules.lumiFilter
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year

# PuWeight:
#     name: puWeightRDF
#     path: Corrections.LUM.puWeight
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod
#         auto: True
#         file: self.get_path(self.get_input())[0] # this is needed only if  auto: True

# EleCorrections_SF:
#     name: eleSFRDF
#     path: Corrections.EGM.eleCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod
#         wps: ["wp80iso"]

# EleCorrections_SS:
#     name: eleSSRDF
#     path: Corrections.EGM.eleCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# MuCorrections:
#     name: muSFRDF
#     path: Corrections.MUO.muCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod
#         wps: ["tight_id", "tight_iso"]

# Now contains a patch to make HHLepton_Selection work but needs to be fixed 
# to properly take into account the WP in the TES evaluation
# i.e. wehn applying TES systematic need to specify ID WP
# TauCorrections:
#     name: tauSFRDF
#     path: Corrections.TAU.tauCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod
#         vsjet_wps: ["Medium", "Tight"]
#         vse_wps: ["VVLoose", "Tight"]
#         vsmu_wps: ["VLoose", "Tight"]
#         vsjet_vse_wp: "VVLoose"

# BTagCorrections:
#     name: btagSFRDF
#     path: Corrections.BTV.btagCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod
#         wps: ['shape', 'M']

# Now work in a patch of TauCorrections but needs to be fixed 
# to properly take into account the WP in the TES evaluation
# HHLepton_Selection:
#     name: HHLeptonRDF
#     path: Tools.Tools.HHLepton
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runEra: self.dataset.runEra
#         tauId_algo: self.config.tauId_algo
#         tauId_algo_wps: self.config.tauId_algo_wps
#         pairType_filter: True

# HHLepton_Variables:
#     name: HHLeptonVarRDF
#     path: Tools.Tools.HHLepton
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year

## FROM HERE UP ALL DONE/TESTED 
############################################
## FROM HERE DOWN ALL TO BE DONE/TESTED 

JmeCorrections_veto:
    name: vetoMapRDF
    path: Corrections.JME.jetCorrections
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        runPeriod: self.config.runPeriod
        apply_veto: True

# JmeCorrections_jec:
#     name: 
#     path: Corrections.JME.jetCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# JmeCorrections_jer:
#     name: 
#     path: Corrections.JME.jetCorrections
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# JmeCorrections_??:
#     name: ??
#     path: Corrections.JME.??
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# HHJet_Selection:
#     name: HHJetsRDF
#     path: Tools.Tools.HHJets
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         extEtaAcc: True
#         btag_algo: self.config.btag_algo
#         btag_algo_wps: self.config.btag_algo_wps
#         bpair_filter: True

# SVfit:
#     name: SVFitRDF
#     path: Tools.Tools.svfit
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# HHKinFit:
#     name: HHKinFitRDF
#     path: Tools.Tools.hh
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# IdAndIsoSF:
#     name: dauIdIsoSFRDF
#     path: Tools.Tools.dauIdIso
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# TrigSF: ???
#     name: Htt_trigSFRDF
#     path: Tools.Tools.Htt_trigSF
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# HHBTagDNN:
#     name: 
#     path: 
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# MulticlassifierDNN:
#     name: HHMulticlassRDF
#     path: Tools.Tools.HHMulticlass
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod

# HHDNN:
#     name: HHDNNRDF 
#     path: Tools.Tools.HHDNN 
#     parameters:
#         isMC: self.dataset.process.isMC
#         year: self.config.year
#         runPeriod: self.config.runPeriod